# Generated by Django 2.2.2 on 2020-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashApp', '0002_auto_20201112_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('bisisness', 'ビジネス'), ('生活', 'life'), ('other', 'その他')], max_length=50),
        ),
    ]
