# Generated by Django 2.2.2 on 2020-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashApp', '0003_auto_20201112_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('bisisness', 'ビジネス'), ('life', '生活'), ('other', 'その他')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('bisisness', 'ビジネス'), ('life', '生活'), ('other', 'その他')], max_length=50),
        ),
    ]
